### ISSUE TITLE
question about Docker for AD MSSQL

### ISSUE THREAD

**Issue by killmasta93** [cviorel/cviorel.com#1]
Hi
I was looking at your guide https://www.cviorel.com/tag/mssql/
But tried to replicate it on docker but for some odd reason i keep getting this error
was wondering if possible to create guide for docker?

Thank you 
```
root@hercules:/# klist
Ticket cache: FILE:/tmp/krb5cc_0
Default principal: administrator@TEST.LOCAL

Valid starting     Expires            Service principal
12/26/23 03:54:34  12/26/23 13:54:34  krbtgt/TEST.LOCAL@TEST.LOCAL
	renew until 12/27/23 03:54:32
12/26/23 03:54:37  12/26/23 13:54:34  MSSQLSvc/hercules.TEST.LOCAL:1433@TEST.LOCAL
	renew until 12/27/23 03:54:32
root@hercules:/# /opt/mssql/bin/mssql-conf validate-ad-config /var/opt/mssql/secrets/mssql.keytab
Error: Cannot contact default realm 'TEST'
Warning: RDNS could not resolve this host. This is not a fatal error, but should be fixed by updating your RDNS records
Traceback (most recent call last):
  File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 598, in <module>
    main()
  File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 594, in main
    processCommands()
  File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 310, in processCommands
    COMMAND_TABLE[args.which]()
  File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 266, in handleValidateADConfig
    config.validate()
  File "/opt/mssql/lib/mssql-conf/mssqlad.py", line 149, in validate
    if self.checkSPNs() != successExitCode:
  File "/opt/mssql/lib/mssql-conf/mssqlad.py", line 376, in checkSPNs
    kvno, ret = self.checkKeytabEntry(spn)
  File "/opt/mssql/lib/mssql-conf/mssqlad.py", line 315, in checkKeytabEntry
    kvno = kvno.split('=')
TypeError: a bytes-like object is required, not 'str'
```

**Comment by cviorel** [comment]
This should work for a standard Docker installation, no additional configuration. Official docker documentation is very detailed.
